# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180103_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号码'),
        ),
    ]
